package br.com.szella.novaluna.service.impl;

import br.com.szella.novaluna.dto.DesafioDto;
import br.com.szella.novaluna.dto.PecaDto;
import br.com.szella.novaluna.dto.TabuleiroCasaDto;
import br.com.szella.novaluna.enums.CorPecaEnum;
import br.com.szella.novaluna.service.CargaInicialService;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static java.util.List.of;

@Service
public class CargaInicialServiceImpl implements CargaInicialService {

    @Override
    public List<PecaDto> iniciarPecas() {
        var pecas = new ArrayList<PecaDto>();

        pecas.addAll(iniciarPecasAmarelo());
        pecas.addAll(iniciarPecasAzul());
        pecas.addAll(iniciarPecasVerde());
        pecas.addAll(iniciarPecasVermelho());

        embaralharPecas(pecas);
        identificarPecas(pecas);

        return pecas;
    }

    @Override
    public TabuleiroCasaDto[] carregarCasa() {
        var casas = new TabuleiroCasaDto[24];
        for (int i = 0; i < 24; i++) {
            casas[i] = TabuleiroCasaDto.builder().build();
        }

        return casas;
    }

    private void embaralharPecas(ArrayList<PecaDto> pecas) {
        for (int i = 1; i <= 5; i++) {
            Collections.shuffle(pecas);
        }
    }

    private void identificarPecas(ArrayList<PecaDto> pecas) {
        var idPeca = 1;
        for (PecaDto peca : pecas) {
            peca.setId(idPeca++);
        }
    }

    private List<PecaDto> iniciarPecasAmarelo() {
        return of(
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(1)
                        .desafios(of())
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().amarelo(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().amarelo(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().vermelho(1).azul(1).amarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().verde(1).amarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().vermelho(1).azul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().verde(1).amarelo(1).vermelho(1).azul(1).build(),
                                DesafioDto.builder().azul(3).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().verde(4).build(),
                                DesafioDto.builder().verde(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().amarelo(3).build(),
                                DesafioDto.builder().vermelho(1).azul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().verde(1).vermelho(1).build(),
                                DesafioDto.builder().azul(1).amarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().verde(3).build(),
                                DesafioDto.builder().vermelho(3).build(),
                                DesafioDto.builder().azul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().vermelho(2).build(),
                                DesafioDto.builder().azul(2).build(),
                                DesafioDto.builder().amarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().verde(2).build(),
                                DesafioDto.builder().vermelho(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().vermelho(3).build(),
                                DesafioDto.builder().vermelho(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().azul(3).build(),
                                DesafioDto.builder().verde(1).azul(1).build(),
                                DesafioDto.builder().verde(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().verde(2).build(),
                                DesafioDto.builder().vermelho(2).build(),
                                DesafioDto.builder().azul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(7)
                        .desafios(of(
                                DesafioDto.builder().verde(1).vermelho(1).build(),
                                DesafioDto.builder().verde(1).azul(1).build(),
                                DesafioDto.builder().vermelho(1).azul(1).build()
                        ))
                        .build());
    }

    private List<PecaDto> iniciarPecasAzul() {
        return of(
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(1)
                        .desafios(of())
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().azul(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().azul(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().verde(1).azul(1).amarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().verde(1).amarelo(1).vermelho(1).azul(1).build(),
                                DesafioDto.builder().vermelho(3).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().amarelo(1).azul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().verde(1).vermelho(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().verde(1).amarelo(1).build(),
                                DesafioDto.builder().vermelho(1).azul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().azul(3).build(),
                                DesafioDto.builder().verde(1).vermelho(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().verde(3).build(),
                                DesafioDto.builder().vermelho(3).build(),
                                DesafioDto.builder().amarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().vermelho(4).build(),
                                DesafioDto.builder().vermelho(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().verde(3).build(),
                                DesafioDto.builder().verde(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().amarelo(2).build(),
                                DesafioDto.builder().verde(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().verde(2).build(),
                                DesafioDto.builder().azul(2).build(),
                                DesafioDto.builder().amarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().verde(2).build(),
                                DesafioDto.builder().vermelho(2).build(),
                                DesafioDto.builder().amarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().amarelo(3).build(),
                                DesafioDto.builder().vermelho(1).amarelo(1).build(),
                                DesafioDto.builder().vermelho(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(7)
                        .desafios(of(
                                DesafioDto.builder().verde(1).vermelho(1).build(),
                                DesafioDto.builder().verde(1).amarelo(1).build(),
                                DesafioDto.builder().vermelho(1).amarelo(1).build()
                        ))
                        .build());
    }

    private List<PecaDto> iniciarPecasVerde() {
        return of(
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(1)
                        .desafios(of())
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().verde(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().verde(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().verde(1).amarelo(1).vermelho(1).azul(1).build(),
                                DesafioDto.builder().amarelo(3).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().azul(1).amarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().vermelho(1).verde(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().verde(1).vermelho(1).amarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().verde(3).build(),
                                DesafioDto.builder().azul(1).amarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().verde(1).amarelo(1).build(),
                                DesafioDto.builder().vermelho(1).azul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().azul(4).build(),
                                DesafioDto.builder().azul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().azul(3).build(),
                                DesafioDto.builder().amarelo(3).build(),
                                DesafioDto.builder().vermelho(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().verde(2).build(),
                                DesafioDto.builder().vermelho(2).build(),
                                DesafioDto.builder().amarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().vermelho(2).build(),
                                DesafioDto.builder().azul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().amarelo(3).build(),
                                DesafioDto.builder().amarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().vermelho(3).build(),
                                DesafioDto.builder().vermelho(1).azul(1).build(),
                                DesafioDto.builder().azul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().azul(2).build(),
                                DesafioDto.builder().amarelo(2).build(),
                                DesafioDto.builder().vermelho(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(7)
                        .desafios(of(
                                DesafioDto.builder().vermelho(1).azul(1).build(),
                                DesafioDto.builder().vermelho(1).amarelo(1).build(),
                                DesafioDto.builder().azul(1).amarelo(1).build()
                        ))
                        .build());
    }

    private List<PecaDto> iniciarPecasVermelho() {
        return of(
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(1)
                        .desafios(of())
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().vermelho(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().vermelho(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().verde(1).vermelho(1).azul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().amarelo(1).verde(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().azul(1).vermelho(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().verde(1).amarelo(1).vermelho(1).azul(1).build(),
                                DesafioDto.builder().verde(3).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().verde(1).vermelho(1).build(),
                                DesafioDto.builder().azul(1).amarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().azul(3).build(),
                                DesafioDto.builder().amarelo(3).build(),
                                DesafioDto.builder().verde(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().vermelho(3).build(),
                                DesafioDto.builder().verde(1).amarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().amarelo(4).build(),
                                DesafioDto.builder().amarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().verde(2).build(),
                                DesafioDto.builder().vermelho(2).build(),
                                DesafioDto.builder().azul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().azul(3).build(),
                                DesafioDto.builder().azul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().azul(2).build(),
                                DesafioDto.builder().amarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().azul(2).build(),
                                DesafioDto.builder().amarelo(2).build(),
                                DesafioDto.builder().verde(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().verde(3).build(),
                                DesafioDto.builder().verde(1).amarelo(1).build(),
                                DesafioDto.builder().amarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(7)
                        .desafios(of(
                                DesafioDto.builder().verde(1).azul(1).build(),
                                DesafioDto.builder().verde(1).amarelo(1).build(),
                                DesafioDto.builder().azul(1).amarelo(1).build()
                        ))
                        .build());
    }
}
