package br.com.szella.novaluna.service.impl;

import br.com.szella.novaluna.dto.DesafioDto;
import br.com.szella.novaluna.dto.PecaDto;
import br.com.szella.novaluna.enums.CorPecaEnum;
import br.com.szella.novaluna.service.CargaInicialService;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

import static java.util.List.of;

@Service
public class CargaInicialServiceImpl implements CargaInicialService {

    @Override
    public List<PecaDto> iniciarPecas() {
        var pecas = new ArrayList<PecaDto>();

        pecas.addAll(iniciarPecasAmarelo());
        pecas.addAll(iniciarPecasAzul());
        pecas.addAll(iniciarPecasVerde());
        pecas.addAll(iniciarPecasVermelho());

        return pecas;
    }

    private List<PecaDto> iniciarPecasAmarelo() {
        return of(
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(1)
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().corAmarelo(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().corAmarelo(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(1).corAzul(1).corAmarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corAmarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(1).corAzul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corAmarelo(1).corVermelho(1).corAzul(1).build(),
                                DesafioDto.builder().corAzul(3).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corVerde(4).build(),
                                DesafioDto.builder().corVerde(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corAmarelo(3).build(),
                                DesafioDto.builder().corVermelho(1).corAzul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corVermelho(1).build(),
                                DesafioDto.builder().corAzul(1).corAmarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corVerde(3).build(),
                                DesafioDto.builder().corVermelho(3).build(),
                                DesafioDto.builder().corAzul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(2).build(),
                                DesafioDto.builder().corAzul(2).build(),
                                DesafioDto.builder().corAmarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corVerde(2).build(),
                                DesafioDto.builder().corVermelho(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(3).build(),
                                DesafioDto.builder().corVermelho(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().corAzul(3).build(),
                                DesafioDto.builder().corVerde(1).corAzul(1).build(),
                                DesafioDto.builder().corVerde(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().corVerde(2).build(),
                                DesafioDto.builder().corVermelho(2).build(),
                                DesafioDto.builder().corAzul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AMARELO)
                        .passos(7)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corVermelho(1).build(),
                                DesafioDto.builder().corVerde(1).corAzul(1).build(),
                                DesafioDto.builder().corVermelho(1).corAzul(1).build()
                        ))
                        .build());
    }

    private List<PecaDto> iniciarPecasAzul() {
        return of(
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(1)
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().corAzul(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().corAzul(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corAzul(1).corAmarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corAmarelo(1).corVermelho(1).corAzul(1).build(),
                                DesafioDto.builder().corVermelho(3).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corAmarelo(1).corAzul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corVermelho(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corAmarelo(1).build(),
                                DesafioDto.builder().corVermelho(1).corAzul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corAzul(3).build(),
                                DesafioDto.builder().corVerde(1).corVermelho(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corVerde(3).build(),
                                DesafioDto.builder().corVermelho(3).build(),
                                DesafioDto.builder().corAmarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(4).build(),
                                DesafioDto.builder().corVermelho(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corVerde(3).build(),
                                DesafioDto.builder().corVerde(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corAmarelo(2).build(),
                                DesafioDto.builder().corVerde(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corVerde(2).build(),
                                DesafioDto.builder().corAzul(2).build(),
                                DesafioDto.builder().corAmarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().corVerde(2).build(),
                                DesafioDto.builder().corVermelho(2).build(),
                                DesafioDto.builder().corAmarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().corAmarelo(3).build(),
                                DesafioDto.builder().corVermelho(1).corAmarelo(1).build(),
                                DesafioDto.builder().corVermelho(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.AZUL)
                        .passos(7)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corVermelho(1).build(),
                                DesafioDto.builder().corVerde(1).corAmarelo(1).build(),
                                DesafioDto.builder().corVermelho(1).corAmarelo(1).build()
                        ))
                        .build());
    }

    private List<PecaDto> iniciarPecasVerde() {
        return of(
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(1)
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().corVerde(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().corVerde(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corAmarelo(1).corVermelho(1).corAzul(1).build(),
                                DesafioDto.builder().corAmarelo(3).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corAzul(1).corAmarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(1).corVerde(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corVermelho(1).corAmarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corVerde(3).build(),
                                DesafioDto.builder().corAzul(1).corAmarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corAmarelo(1).build(),
                                DesafioDto.builder().corVermelho(1).corAzul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corAzul(4).build(),
                                DesafioDto.builder().corAzul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corAzul(3).build(),
                                DesafioDto.builder().corAmarelo(3).build(),
                                DesafioDto.builder().corVermelho(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corVerde(2).build(),
                                DesafioDto.builder().corVermelho(2).build(),
                                DesafioDto.builder().corAmarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(2).build(),
                                DesafioDto.builder().corAzul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corAmarelo(3).build(),
                                DesafioDto.builder().corAmarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(3).build(),
                                DesafioDto.builder().corVermelho(1).corAzul(1).build(),
                                DesafioDto.builder().corAzul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().corAzul(2).build(),
                                DesafioDto.builder().corAmarelo(2).build(),
                                DesafioDto.builder().corVermelho(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERDE)
                        .passos(7)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(1).corAzul(1).build(),
                                DesafioDto.builder().corVermelho(1).corAmarelo(1).build(),
                                DesafioDto.builder().corAzul(1).corAmarelo(1).build()
                        ))
                        .build());
    }

    private List<PecaDto> iniciarPecasVermelho() {
        return of(
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(1)
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(2)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(4).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corVermelho(1).corAzul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corAmarelo(1).corVerde(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corAzul(1).corVermelho(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(3)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corAmarelo(1).corVermelho(1).corAzul(1).build(),
                                DesafioDto.builder().corVerde(3).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corVermelho(1).build(),
                                DesafioDto.builder().corAzul(1).corAmarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corAzul(3).build(),
                                DesafioDto.builder().corAmarelo(3).build(),
                                DesafioDto.builder().corVerde(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corVermelho(3).build(),
                                DesafioDto.builder().corVerde(1).corAmarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(4)
                        .desafios(of(
                                DesafioDto.builder().corAmarelo(4).build(),
                                DesafioDto.builder().corAmarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corVerde(2).build(),
                                DesafioDto.builder().corVermelho(2).build(),
                                DesafioDto.builder().corAzul(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corAzul(3).build(),
                                DesafioDto.builder().corAzul(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(5)
                        .desafios(of(
                                DesafioDto.builder().corAzul(2).build(),
                                DesafioDto.builder().corAmarelo(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().corAzul(2).build(),
                                DesafioDto.builder().corAmarelo(2).build(),
                                DesafioDto.builder().corVerde(1).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(6)
                        .desafios(of(
                                DesafioDto.builder().corVerde(3).build(),
                                DesafioDto.builder().corVerde(1).corAmarelo(1).build(),
                                DesafioDto.builder().corAmarelo(2).build()
                        ))
                        .build(),
                PecaDto.builder()
                        .cor(CorPecaEnum.VERMELHO)
                        .passos(7)
                        .desafios(of(
                                DesafioDto.builder().corVerde(1).corAzul(1).build(),
                                DesafioDto.builder().corVerde(1).corAmarelo(1).build(),
                                DesafioDto.builder().corAzul(1).corAmarelo(1).build()
                        ))
                        .build());
    }
}
